version: "3.7"
services:
  node-router:
    image: node:12-slim
    restart: unless-stopped
    command: npm run start:router
    working_dir: /usr/src/service
    volumes:
      - type: bind
        source: .
        target: /usr/src/service
    environment:
      - NODE_ENV=development
      - HTTPS=0
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - DOCKER_CONTAINER=1
    networks:
      - local-shared-net
    ports:
      - "80:80"
      - "443:443"
      - "60001:60001"
  node-client:
        image: node:12-slim
        restart: unless-stopped
        command: npm run start:client
        working_dir: /usr/src/service
        volumes:
          - type: bind
            source: .
            target: /usr/src/service
        environment:
          - NODE_FILE=src/conf/hosts.json
        networks:
          - local-shared-net
networks:
  local-shared-net:
    driver: bridge
