version: "3.7"
services:
  node-router:
    image: node:12-slim
    restart: unless-stopped
    command: npm run start:router
    working_dir: /usr/src/service
    volumes:
      - type: bind
        source: .
        target: /usr/src/service
    environment:
      - NODE_ENV=development
      - HTTPS=0
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - DOCKER_CONTAINER=1
      - NR_LOG_DEBUG=1
    networks:
      local-shared-net:
        aliases:
          - noderouter.localhost
    ports:
      - "80:80"
      - "443:443"
      - "4010:4010"
  nr-client:
    image: node:12-slim
    restart: unless-stopped
    command: npm run start:client
    working_dir: /usr/src/service
    volumes:
      - type: bind
        source: .
        target: /usr/src/service
    environment:
      - NR_HOSTS_FILE=src/conf/dist/hosts.json
      - DOCKER_CONTAINER=1
      - NR_LOG_DEBUG=1
    networks:
      - local-shared-net
  whoami:
    image: emilevauge/whoami # A container that exposes an API to show it's IP address
    hostname: whoami.localhost
    container_name: whoami
    restart: always
    networks:
      local-shared-net:
        aliases:
          - whoami.localhost
    ports:
      - "4011:80"
    expose:
      - 80
  portainer:
    image: portainer/portainer
    hostname: portainer.localhost
    container_name: portainer
    restart: always
    networks:
      local-shared-net:
        aliases:
          - portainer.localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - "4012:9000"
    expose:
      - 9000
networks:
  local-shared-net:
    driver: bridge
    name: "local-shared-net"
